# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: walter9809
# "service" is the name of this project. This will also be added to your AWS resource names.
service: reto-tecnico-seguros

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:390403884591:table/SeguroTable

functions:
  calcular:
    handler: dist/cotizacion/cotizacion.controller.calcularCotizacion
    events:
      - httpApi:
          path: /salud/calcularCotizacion
          method: post        


custom:
  typescript:
    tsConfigFile: tsconfig.json  

resources:
      Resources:
        usersTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: SeguroTable
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH

plugins:
  - serverless-plugin-typescript
  - serverless-offline           